---
title: "Examen2-R"
author: "Daniela Prado Vargas"
format: html
editor: visual
---
Carga paquetes y definir paleta para gráficos
```{r}
library(tidyverse)
paleta <- c("#FEEA08", "#203667", "#2957A4", "#9DD5E4", "#9A9899", "#6AB04A")
```

1. Abrir tabla
```{r}
moras <- read.table("C:/Users/danie/OneDrive/Escritorio/examen2/moras.txt",
                       header = TRUE,
                       sep = ",",
                       stringsAsFactors = FALSE)
```

2. Resumen de las variables numéricas
```{r}
moras$SALARIO <- as.numeric(gsub(",", ".", moras$SALARIO))
resumen <- summary(moras[sapply(moras, is.numeric)]) 
resumen
```
3. Identificar valores atípicos
```{r}
moras <- moras %>%
  mutate(
    Z_Salario = (SALARIO - mean(SALARIO, na.rm = TRUE)) / sd(SALARIO, na.rm = TRUE),
    Outlier_Salario = ifelse(abs(Z_Salario) > 1.96, "Sí", "No"),
    
    Z_Edad = (EDAD - mean(EDAD, na.rm = TRUE)) / sd(EDAD, na.rm = TRUE),
    Outlier_Edad = ifelse(abs(Z_Edad) > 1.96, "Sí", "No")
  )
```

4. Detección de valores faltantes por colummna
```{r}
moras$TIPO_ASEGURAMIENTO <- na_if(trimws(moras$TIPO_ASEGURAMIENTO), "")
#De excel se detectó que aquí habían NA y al hacer el cálculo de porcentajes salía cero. Al revisar de forma manual me di cuenta que había como un "espacio", por lo que R no lo tomaba como NA.
moras %>%
  summarise(across(everything(), ~mean(is.na(.)) * 100))
```
5. Imputación de valores faltates
```{r}
conteo <- moras %>%
  filter(!is.na(TIPO_ASEGURAMIENTO)) %>%
  count(TIPO_ASEGURAMIENTO) %>%
  arrange(desc(n))

moda_tipo <- conteo$TIPO_ASEGURAMIENTO[1]          

moras <- moras %>%
  mutate(
    SALARIO = ifelse(is.na(SALARIO), mean(SALARIO, na.rm = TRUE), SALARIO),
    EDAD = ifelse(is.na(EDAD), mean(EDAD, na.rm = TRUE), EDAD),
    TIPO_ASEGURAMIENTO = ifelse(is.na(TIPO_ASEGURAMIENTO), moda_tipo, TIPO_ASEGURAMIENTO)
    )
```
6. Gráficos de cantidad de individuos por cada categoría
```{r}
# Tipo de Aseguramiento
ggplot(moras, aes(x = TIPO_ASEGURAMIENTO)) +
  geom_bar(fill = paleta[1:6]) +
  labs(title = "Cantidad de individuos por Tipo de Aseguramiento",
       x = "Tipo de Aseguramiento",
       y = "Cantidad de personas") +
  theme_minimal() +
  coord_flip()

# Sexo
ggplot(moras, aes(x = SEXO)) +
  geom_bar(fill = paleta[2:3]) +
  labs(title = "Cantidad de individuos por Sexo",
       x = "Sexo",
       y = "Cantidad de personas") +
  theme_minimal()

# Sector
ggplot(moras, aes(x = SECTOR)) +
  geom_bar(fill = paleta[2:3]) +
  labs(title = "Cantidad de individuos por Sector",
       x = "Sector",
       y = "Cantidad de personas") +
  theme_minimal()

# Activo seguro
ggplot(moras, aes(x = INDICADOR_ACTIVO)) +
  geom_bar(fill = paleta[2:3]) +
  labs(title = "Cantidad de individuos según actividad del seguro",
       x = "Seguro activo",
       y = "Cantidad de personas") +
  theme_minimal()

# Extranjeros
ggplot(moras, aes(x = INDICADOR.EXTRANJERO)) +
  geom_bar(fill = paleta[2:3]) +
  labs(title = "Cantidad de individuos por nacionalidad",
       x = "Extranjeros",
       y = "Cantidad de personas") +
  theme_minimal()
```
7. Porcentaje de morosos por clase
```{r}
resumen_morosos <- function(df, variable) {
  df %>%
    group_by(.data[[variable]]) %>%
    summarise(
      TOTAL = n(),
      MOROSOS = sum(INDICADOR_MOROSO == "SI"),
      PORCENTAJE = round((MOROSOS / TOTAL) * 100, 2)
    ) %>%
    rename(CATEGORIA = .data[[variable]])
}

grafico_morosos <- function(df, variable) {
  datos <- resumen_morosos(df, variable)
  
  if(variable == "TIPO_ASEGURAMIENTO") {
    abrev <- c(
      "ASALARIADO" = "ASALARIADO",
      "PENSIONADOS EN SU PROPIO SISTEMA" = "PENSIONADOS",
      "ASEGURADO VOLUNTARIO" = "VOLUNTARIOS",
      "TRABAJADOR INDEPENDIENTE" = "INDEPENDIENTE",
      "CONVENIOS ESPECIALES DE TRABAJADORES INDEPENDIENTES" = "CONV. ESP. INDEPENDIENTES",
      "CONVENIOS ESPECIALES DE ASEGURADOS VOLUNTARIOS" = "CONV. ESP. VOLUNTARIOS"
    )
    datos$CATEGORIA <- abrev[datos$CATEGORIA]
  }
  
  ggplot(datos, aes(x = CATEGORIA, y = PORCENTAJE, fill = CATEGORIA)) +
    geom_col() +
    coord_flip() +
    scale_fill_manual(values = paleta) +
    theme_minimal(base_size = 13) +
    theme(
      legend.position = "none",
      plot.title = element_text(size = 14, hjust = 0.5, margin = margin(b = 10))
    ) +
    labs(title = paste("Porcentaje de morosos por", variable),
         x = "",
         y = "Procentaje de Morosos")
}

grafico_morosos(moras, "TIPO_ASEGURAMIENTO")
grafico_morosos(moras, "SEXO")
grafico_morosos(moras, "SECTOR")
grafico_morosos(moras, "INDICADOR_ACTIVO")
grafico_morosos(moras, "INDICADOR.EXTRANJERO")
```





